---
title: "team"
---

# Meet the Team

Our project is led by a diverse team of experts from various fields:

-   Ali Ari is a Professor of Economics at Department of Political Science and Public Administration at Marmara University. Before joining Marmara University, Dr. Ari served as the Director of the Centre for European Studies and as the Chair of Department of Economics at Kirklareli University. He was a visiting scholar at Rice University in 2018 and gave lectures as a visiting professor at Taras Shevchenko National University of Kiev, University of Debrecen, Toulon University, and Yeditepe University. 
Dr. Ari received his B.A. in politics from Marmara University in 2002 and both his M.A. (2003) and his Ph.D. (2009) in economics from Toulon University. Dr. Ari’s main research interests are in financial crises, energy, trade, political economy, and Turkish economy. Dr. Ari, who served as an assessor for the Jean Monnet Scholarship Program and the Vice-Director of Graduate School in Social Sciences at Marmara University, worked as a researcher for the project on reducing greenhouse gas emissions in Turkey, financed by the Ministry of Environment, Urbanism and Climate Change. Dr. Ari currently serves as the Director of French Program of Political Science and the Director of Research Centre on France-Turkey Relations

-   Caner Demir is an Associate Professor of Economics at Manisa Celal Bayar University, Türkiye. He received his BA in Economics from Dokuz Eylul University, Türkiye and his PhD in Economics from Ege University, Türkiye. He has been at the University of Verona for 3 months and at the University of Massachusetts-Amherst for 12 months as a visiting scholar. His areas of research include economic growth, economics of innovation, international capital movements, and environmental economics.

-   Hakan Mehmetcik is an Associate Professor of International Relations at Marmara University’s Faculty of Political Science. He has a Ph.D. in political science and international relations from Yildiz Technical University. His research interest covers Social Data Science, Computational IR, Qualitative and Quantitative Methods in Social Sciences along with Comparative Regionalism and Regional Order, International Political Economy, and Global Governance in broader IR literature. 

-   Nazan Cömert Baechler currently works as a researcher-lecturer in social sciences at Marmara University in the Department of Political Science and Public Administration. Since 2021 she has been collaborating with CIFE European Institute as an associated lecturer in the Master’s programme in Advanced European and International Studies, where she teaches courses on disaster risk management in Mediterranean cities and public policies. She also works as a visitor lecturer in the Housing in Europe Master’s programme at the University of Le Havre (France). Her work as a researcher and lecturer draws on a multidisciplinary approach to risk, the academic focus being specifically on vulnerability analysis, disaster risk management and vulnerable groups, public policy for adapting cities to climate change. Nazan Cömert Baechler has been involved for more than 20 years as an expert in several projects concerning risk reduction and public policy such as LAR III (Local Administration Reform) funded by the EU; TÜBİTAK 1001 Project “Earthquakes and Women: Determining the Factors for a Social Vulnerability Sensitive Earthquake Disaster Planning for Istanbul: Diagnosis, Analysis and Solutions”; and MERP Project (Marmara Earthquake Reconstruction Project) funded by CE

-   Raif Cergibozan is a professor of Economics at Kirklareli University, Türkiye. He earned his bachelor’s degree in Economics from Marmara University in 2009 and received a master’s degree in Economics from Istanbul Technical University in 2011. Dr. Cergibozan holds two PhD degrees in Economics. He completed his first PhD in Economics at Galatasaray University in 2015 and got the second PhD in Economics at Paris Nanterre University in 2018. His areas of special interest are, energy economics, environmental economics, financial crises, labour markets, international trade, time series analysis, and macro-econometric models.
